#API call for listing Turf

###
GET  http://127.0.0.1:8000/turf/
Accept:  application/json
Authorization: Basic turfadmin:turfadmin

#API call for adding Turf details
###
POST http://127.0.0.1:8000/turf/
Content-Type: application/json
Authorization: Basic turfadmin:turfadmin

  {
    "name": "Goal Arena",
    "location": "kasargod",
    "phone": "9876543212",
    "fee": 1000
  }

#API call for fetching Turf

###
GET  http://127.0.0.1:8000/turf/2/
Accept:  application/json
Authorization: Basic turfadmin:turfadmin



#API call for updating turf details
###
PUT  http://127.0.0.1:8000/turf/2/
Content-Type: application/json
Authorization:  Basic turfadmin:turfadmin

 {
    "name": "Arena",
    "location": "wayanad",
    "phone": "9876543212",
    "fee": 1000
  }




#===============ADMIN==================
#API call for creating admin user

###
POST  http://127.0.0.1:8000/admin-register/
Content-Type: application/json


{
    "username": "turfadmin",
    "email": "turfadmin@gmail.com",
    "password":"turfadmin"
  }



#============Turf_Bookings=============

#API call for listing turf
###
GET  http://127.0.0.1:8000/booking-turf/
Accept:  application/json
Authorization: Basic turfadmin:turfadmin